export const LETTER_VALUES = {
  A: 1,
  B: 2,
  C: 3,
  D: 4,
  E: 5,
  F: 6,
  G: 7,
  H: 8,
  I: 9,
  J: 1,
  K: 2,
  L: 3,
  M: 4,
  N: 5,
  O: 6,
  P: 7,
  Q: 8,
  R: 9,
  S: 1,
  T: 2,
  U: 3,
  V: 4,
  W: 5,
  X: 6,
  Y: 7,
  Z: 8,
}

export const MASTER_NUMBERS = [11, 22, 33]

export const NUMBER_MEANINGS = {
  1: {
    title: "El Líder",
    description: "Independencia, liderazgo, pionero, iniciativa",
    keywords: ["Liderazgo", "Independencia", "Innovación", "Determinación"],
    color: "#FF6B6B",
    element: "Fuego",
  },
  2: {
    title: "El Cooperador",
    description: "Cooperación, diplomacia, sensibilidad, armonía",
    keywords: ["Cooperación", "Diplomacia", "Sensibilidad", "Paz"],
    color: "#4ECDC4",
    element: "Agua",
  },
  3: {
    title: "El Comunicador",
    description: "Creatividad, comunicación, expresión, optimismo",
    keywords: ["Creatividad", "Comunicación", "Alegría", "Expresión"],
    color: "#45B7D1",
    element: "Aire",
  },
  4: {
    title: "El Constructor",
    description: "Estabilidad, trabajo duro, organización, disciplina",
    keywords: ["Estabilidad", "Disciplina", "Organización", "Trabajo"],
    color: "#96CEB4",
    element: "Tierra",
  },
  5: {
    title: "El Aventurero",
    description: "Libertad, aventura, curiosidad, versatilidad",
    keywords: ["Libertad", "Aventura", "Curiosidad", "Cambio"],
    color: "#FFEAA7",
    element: "Fuego",
  },
  6: {
    title: "El Cuidador",
    description: "Responsabilidad, cuidado, familia, servicio",
    keywords: ["Responsabilidad", "Familia", "Servicio", "Amor"],
    color: "#DDA0DD",
    element: "Tierra",
  },
  7: {
    title: "El Místico",
    description: "Espiritualidad, introspección, análisis, sabiduría",
    keywords: ["Espiritualidad", "Sabiduría", "Análisis", "Misterio"],
    color: "#9B59B6",
    element: "Agua",
  },
  8: {
    title: "El Ejecutivo",
    description: "Poder material, ambición, logros, autoridad",
    keywords: ["Poder", "Ambición", "Logros", "Autoridad"],
    color: "#E17055",
    element: "Tierra",
  },
  9: {
    title: "El Humanitario",
    description: "Compasión, generosidad, sabiduría universal, servicio",
    keywords: ["Compasión", "Generosidad", "Sabiduría", "Servicio"],
    color: "#00B894",
    element: "Fuego",
  },
  11: {
    title: "El Visionario",
    description: "Intuición elevada, inspiración, iluminación espiritual",
    keywords: ["Intuición", "Inspiración", "Visión", "Espiritualidad"],
    color: "#A29BFE",
    element: "Aire",
  },
  22: {
    title: "El Maestro Constructor",
    description: "Construcción en gran escala, visión práctica, liderazgo mundial",
    keywords: ["Maestría", "Construcción", "Visión", "Liderazgo"],
    color: "#FD79A8",
    element: "Tierra",
  },
  33: {
    title: "El Maestro Sanador",
    description: "Sanación universal, compasión elevada, servicio desinteresado",
    keywords: ["Sanación", "Compasión", "Servicio", "Maestría"],
    color: "#FDCB6E",
    element: "Agua",
  },
}

export const TAROT_CORRESPONDENCES = {
  1: { card: "El Mago", arcana: "Arcano Mayor I" },
  2: { card: "La Sacerdotisa", arcana: "Arcano Mayor II" },
  3: { card: "La Emperatriz", arcana: "Arcano Mayor III" },
  4: { card: "El Emperador", arcana: "Arcano Mayor IV" },
  5: { card: "El Hierofante", arcana: "Arcano Mayor V" },
  6: { card: "Los Enamorados", arcana: "Arcano Mayor VI" },
  7: { card: "El Carro", arcana: "Arcano Mayor VII" },
  8: { card: "La Justicia", arcana: "Arcano Mayor VIII" },
  9: { card: "El Ermitaño", arcana: "Arcano Mayor IX" },
  11: { card: "La Fuerza", arcana: "Arcano Mayor XI" },
  22: { card: "El Loco", arcana: "Arcano Mayor 0/22" },
  33: { card: "El Mundo", arcana: "Arcano Mayor XXI" },
}

export const KABBALAH_CORRESPONDENCES = {
  1: { sephira: "Kether", meaning: "Corona", path: "Unidad Divina" },
  2: { sephira: "Chokmah", meaning: "Sabiduría", path: "Sabiduría Divina" },
  3: { sephira: "Binah", meaning: "Entendimiento", path: "Comprensión" },
  4: { sephira: "Chesed", meaning: "Misericordia", path: "Amor y Bondad" },
  5: { sephira: "Geburah", meaning: "Severidad", path: "Fuerza y Disciplina" },
  6: { sephira: "Tiphereth", meaning: "Belleza", path: "Armonía y Equilibrio" },
  7: { sephira: "Netzach", meaning: "Victoria", path: "Eternidad" },
  8: { sephira: "Hod", meaning: "Gloria", path: "Esplendor" },
  9: { sephira: "Yesod", meaning: "Fundamento", path: "Base de la Manifestación" },
  11: { sephira: "Daath", meaning: "Conocimiento", path: "Conocimiento Oculto" },
  22: { sephira: "Ain Soph", meaning: "Sin Límite", path: "Infinito" },
  33: { sephira: "Ain Soph Aur", meaning: "Luz Sin Límite", path: "Luz Infinita" },
}

export const ASTROLOGY_CORRESPONDENCES = {
  1: { planet: "Sol", sign: "Leo", quality: "Fuego Fijo" },
  2: { planet: "Luna", sign: "Cáncer", quality: "Agua Cardinal" },
  3: { planet: "Júpiter", sign: "Sagitario", quality: "Fuego Mutable" },
  4: { planet: "Urano", sign: "Acuario", quality: "Aire Fijo" },
  5: { planet: "Mercurio", sign: "Géminis", quality: "Aire Mutable" },
  6: { planet: "Venus", sign: "Tauro", quality: "Tierra Fijo" },
  7: { planet: "Neptuno", sign: "Piscis", quality: "Agua Mutable" },
  8: { planet: "Saturno", sign: "Capricornio", quality: "Tierra Cardinal" },
  9: { planet: "Marte", sign: "Aries", quality: "Fuego Cardinal" },
  11: { planet: "Urano", sign: "Acuario", quality: "Aire Fijo Elevado" },
  22: { planet: "Plutón", sign: "Escorpio", quality: "Agua Fijo Transformador" },
  33: { planet: "Neptuno", sign: "Piscis", quality: "Agua Mutable Trascendente" },
}
